---
- name: Deploy application
  hosts: all
  tasks:
    - name: Test connection
      ansible.builtin.ping:

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: yes

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      become: yes

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Reset SSH connection to pick up new group membership
      meta: reset_connection

    - name: Ensure compose directory is setup
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/compose/{{ project_name }}"
        state: directory

    - name: Ensure compose file exists
      ansible.builtin.copy:
        dest: "/home/{{ ansible_user }}/compose/{{ project_name }}/compose.yaml"
        content: "{{ compose_content }}"

    - name: Ensure mounted files exist
      ansible.builtin.copy:
        dest: "/home/{{ ansible_user }}/compose/{{ project_name }}/files/"
        src: "/tmp/{{ item }}"
      with_items: "{{ compose_files }}"

    - name: Docker start compose file
      ansible.builtin.command: 'docker compose --project-directory up "/home/{{ ansible_user }}/compose/{{ project_name }}" --remove-orphans --wait --wait-timeout 120 --yes'
